# Second attempt at making a linear regression model

In [39]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn import linear_model

In [40]:
data = pd.read_csv('data.csv')

In [41]:
data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [42]:
data.drop(columns = ['date','country','statezip'], inplace = True)

In [43]:
encoder = LabelEncoder()

data['street_encoded'] = encoder.fit_transform(data['street']) + 1
data['city_encoded'] = encoder.fit_transform(data['city']) + 1

data = pd.get_dummies(data, columns = ['street_encoded','city_encoded'], drop_first = True)

data.drop(columns = ['street','city'], inplace = True)
data.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,city_encoded_35,city_encoded_36,city_encoded_37,city_encoded_38,city_encoded_39,city_encoded_40,city_encoded_41,city_encoded_42,city_encoded_43,city_encoded_44
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,...,False,False,True,False,False,False,False,False,False,False
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,...,False,True,False,False,False,False,False,False,False,False
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,...,False,False,False,False,False,False,False,False,False,False
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,...,False,False,False,False,False,False,False,False,False,False
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,...,False,False,False,False,False,False,False,False,False,False

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Columns: 4580 entries, price to city_encoded_44
dtypes: bool(4567), float64(4), int64(9)
memory usage: 20.5 MB

In [45]:
data = data[data['price'] < 1000000]

data = data[data['sqft_lot'] < 100000]

In [46]:
data['house_age'] = 2026 - data['yr_built']
data.drop(columns = ['yr_built'], inplace = True)

data['renovation_age'] = np.where(data['yr_renovated'] > 0, 2026 - data['yr_renovated'], 0)
data.drop(columns = ['yr_renovated'], inplace = True)

In [47]:
data.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,city_encoded_37,city_encoded_38,city_encoded_39,city_encoded_40,city_encoded_41,city_encoded_42,city_encoded_43,city_encoded_44,house_age,renovation_age
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,...,True,False,False,False,False,False,False,False,71,21
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,...,False,False,False,False,False,False,False,False,60,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,...,False,False,False,False,False,False,False,False,63,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,...,False,False,False,False,False,False,False,False,50,34
5,490000.0,2.0,1.00,880,6380,1.0,0,0,3,880,...,False,False,False,False,False,False,False,False,88,32

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4171 entries, 0 to 4599
Columns: 4580 entries, price to renovation_age
dtypes: bool(4567), float64(4), int64(9)
memory usage: 18.6 MB

In [49]:
data.count()

price              4171
bedrooms           4171
bathrooms          4171
sqft_living        4171
sqft_lot           4171
                   ...
city_encoded_42    4171
city_encoded_43    4171
city_encoded_44    4171
house_age          4171
renovation_age     4171
Length: 4580, dtype: int64

In [50]:
X = data.drop(columns = ['price'])
Y = data['price']

In [51]:
#scaler = StandardScaler()

#X = scaler.fit_transform(X)

In [52]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state = 42)

In [53]:
model = linear_model.LinearRegression()

In [54]:
model.fit(X_train, Y_train)

LinearRegression()

In [55]:
data.shape

(4171, 4580)

In [56]:
Y_pred = model.predict(X_test)

In [57]:
print('coefficent',model.coef_)
print('intercept',model.intercept_)
print('R2 score',r2_score(Y_test,Y_pred))
print('Mean Squared Error',mean_squared_error(Y_test,Y_pred))

coefficent [ 7458.54741309 -1274.76659224    62.27735348 ... 59955.00674164
  -510.86168946   -64.2709216 ]
intercept 86762.08921801997
R2 score 0.5229261052292552
Mean Squared Error 19863807009.613426