# This is our third attemp at making a linear regression model with Zillow to20 states data.

### Imports

In [1]:
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Data loading

In [2]:
data = pd.read_csv("zillow_top20_states.csv")
data.head()

        zpid state_code  ...      open_house_date is_featured
0   17264897         CA  ...                  NaN       False
1   20021372         CA  ...  2026-02-08T12:00:00       False
2   20009320         CA  ...                  NaN       False
3  460204882         CA  ...                  NaN       False
4   20769150         CA  ...                  NaN       False

[5 rows x 22 columns]

### Encode columns

In [ ]:
#encoder
le = LabelEncoder()

#columns to encode
to_encode = ['state_code','state_name','address','street','city','status','home_type']

#for loop to loop through columns
for col in to_encode:
    data[col] = le.fit_transform(data[col]) + 1

In [6]:
data.head()

        zpid  state_code  ...      open_house_date  is_featured
0   17264897           2  ...                  NaN        False
1   20021372           2  ...  2026-02-08T12:00:00        False
2   20009320           2  ...                  NaN        False
3  460204882           2  ...                  NaN        False
4   20769150           2  ...                  NaN        False

[5 rows x 22 columns]

### drop unnecessary columns

In [ ]:
#drop columnsd
data.drop(columns = ['price_formatted','detail_url','has_open_house','open_house_date'], inplace = True)

In [8]:
data.head()

        zpid  state_code  state_name  ...  days_on_zillow  zestimate  is_featured
0   17264897           2           2  ...               5   455500.0        False
1   20021372           2           2  ...               8        NaN        False
2   20009320           2           2  ...               8  1695500.0        False
3  460204882           2           2  ...               4        NaN        False
4   20769150           2           2  ...               5   999900.0        False

[5 rows x 18 columns]

In [10]:
data.shape

(2214, 18)